modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/OrderedChaos-Dev/Wards/issues"
license="lol"

[[mods]]
	modId="wards"
	version="${version}"
	displayName="Wards"
	displayURL="https://www.orderedchaos.dev/"
	logoFile="wards.png"
	authors="ordered_chaos_dev"
	description='''
	wards!
	'''
[[dependencies.wards]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.wards]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,]"
    ordering="NONE"
    side="BOTH"
